#include "config.h"
#include <memory.h>
#include <intrin.h>
#include <vector>
#include <functional>
#include <fstream>
#include <iostream>
#include <list>
#include <map>
#include <algorithm>
#include <ctime>
#include <boost/algorithm/string.hpp>
#include <boost/lexical_cast.hpp>